name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -e .[dev] numpy
      - run: ruff check .
      - run: pytest --cov=search --cov-report=term --cov-fail-under=90
      - run: pytest -q --cov=search --cov=sudoku --cov=rl_qlearning --cov-report=xml 